Repository HaxeFoundation/haxe, pull requests merged in 2019-12, with the labels that each got.

#9005 Make haxe.Error more generic
  std/asys/AsyncFileSystem.hx
  std/asys/FileSystem.hx
  std/asys/FileWatcher.hx
  std/asys/Process.hx
  std/asys/io/AsyncFile.hx
  std/asys/io/File.hx
  std/asys/io/IpcSerializer.hx
  std/asys/io/IpcUnserializer.hx
  std/asys/net/Server.hx
  std/asys/net/Socket.hx
  std/asys/net/UdpSocket.hx
  std/asys/uv/UVError.hx
  std/asys/uv/UVErrorType.hx
  std/haxe/Error.hx
  std/haxe/ErrorType.hx
  std/haxe/async/Callback.hx
Labels: feature-asys

#9006 [js] use abstract's own type path for generating its impl class (closes #9003)
  src/generators/genjs.ml
Labels: enhancement, feature-abstracts, platform-javascript

#9008 Change `NoData` internal type.
  std/haxe/NoData.hx
Labels: feature-asys

#9050 [js] do not add abstract implementation classes to $hxClasses (closes #7879)
  src/generators/genjs.ml
Labels: enhancement, platform-javascript
