Repository HaxeFoundation/haxe, pull requests merged in 2019-05, with the labels that each got.

#8239 Fix non-BMP characters in StringBuf
  std/cs/_std/StringBuf.hx
  std/java/_std/StringBuf.hx
  tests/unit/src/unitstd/StringBuf.unit.hx
Labels: unicode

#8244 target.unicode define
  src/compiler/main.ml
  src/context/common.ml
  std/haxe/crypto/Md5.hx
  std/haxe/crypto/Sha1.hx
  std/haxe/crypto/Sha256.hx
  std/haxe/format/JsonParser.hx
  std/haxe/xml/Parser.hx
  tests/unit/src/unit/issues/Issue7449.hx
  tests/unit/src/unitstd/String.unit.hx
  tests/unit/src/unitstd/Unicode.unit.hx
  tests/unit/src/unitstd/haxe/iterators/StringIteratorUnicode.unit.hx
  tests/unit/src/unitstd/haxe/iterators/StringKeyValueIteratorUnicode.unit.hx
Labels: unicode

#8238 Surrogates in JSON
  std/haxe/format/JsonParser.hx
  tests/unit/src/unit/TestJson.hx
Labels: unicode

#8251 [flash] always use DoABC tag
  src/core/define.ml
  src/generators/genswf.ml
Labels: platform-flash

#8256 [flash] generate protected namespace for classes that have protected methods anywhere in their heritage (closes #8248)
  src/generators/genswf9.ml
  tests/unit/src/unit/issues/Issue8248.hx
Labels: platform-flash

#8259 add @:bypassAccessor (closes #5039)
  src/context/typecore.ml
  src/core/meta.ml
  src/typing/fields.ml
  src/typing/typeloadModule.ml
  src/typing/typer.ml
  tests/misc/projects/Issue5039/Main.hx
  tests/misc/projects/Issue5039/Main2.hx
  tests/misc/projects/Issue5039/compile-fail.hxml
  tests/misc/projects/Issue5039/compile-fail.hxml.stderr
  tests/misc/projects/Issue5039/compile2-fail.hxml
  tests/misc/projects/Issue5039/compile2-fail.hxml.stderr
  tests/unit/src/unit/issues/Issue5039.hx
Labels: enhancement

#8304 [matcher] fixed position of matched enum arguments
  src/typing/matcher.ml
  tests/misc/projects/Issue7333/compile-fail.hxml.stderr
Labels: feature-pattern-matching

#8309 [lua] changed __name__ and __ename__ to strings instead of tables
  src/generators/genlua.ml
  std/Math.hx
  std/lua/_std/Std.hx
  std/lua/_std/Type.hx
Labels: platform-lua

#8313 [eval] emit user-friendly exception on infinite recursion
  src/macro/eval/evalEmitter.ml
  src/macro/eval/evalExceptions.ml
Labels: platform-eval

#8338 Respect `@:pure(false)` on var fields
  src/context/display/diagnostics.ml
  src/context/purityState.ml
  src/optimization/analyzer.ml
  src/optimization/analyzerTexpr.ml
  src/optimization/analyzerTexprTransformer.ml
  src/optimization/optimizerTexpr.ml
  tests/optimization/src/issues/Issue8226.hx
Labels: feature-analyzer

#8298 UnicodeString
  src/macro/eval/evalHash.ml
  src/macro/eval/evalStdLib.ml
  std/StringTools.hx
  std/UnicodeString.hx
  std/cpp/_std/haxe/Utf8.hx
  std/cpp/cppia/HostClasses.hx
  std/eval/_std/haxe/Utf8.hx
  std/haxe/Utf8.hx
  std/haxe/format/JsonPrinter.hx
  std/haxe/iterators/StringIteratorUnicode.hx
  std/haxe/iterators/StringKeyValueIteratorUnicode.hx
  std/neko/Utf8.hx
  std/php/_std/haxe/Utf8.hx
  tests/unit/src/unit/TestJson.hx
  tests/unit/src/unit/UnitBuilder.hx
  tests/unit/src/unitstd/UnicodeString.unit.hx
  tests/unit/src/unitstd/haxe/Utf8.unit.hx
Labels: unicode

#8349 Add string comparison unit tests
  tests/unit/src/unitstd/String.unit.hx
Labels: unicode
