Repository HaxeFoundation/haxe, pull requests merged in 2020-02, with the labels that each got.

#9009 [WIP] SSL support for eval
  Makefile
  Makefile.win
  extra/azure-pipelines/build-linux.yml
  extra/azure-pipelines/build-mac.yml
  extra/azure-pipelines/build-windows.yml
  libs/mbedtls/dune
  libs/mbedtls/mbedtls.ml
  libs/mbedtls/mbedtls_stubs.c
  src/dune
  src/macro/eval/evalHash.ml
  src/macro/eval/evalSsl.ml
  src/macro/eval/evalStdLib.ml
  src/macro/eval/evalValue.ml
  std/eval/_std/mbedtls/Config.hx
  std/eval/_std/mbedtls/CtrDrbg.hx
  std/eval/_std/mbedtls/Entropy.hx
  std/eval/_std/mbedtls/Error.hx
  std/eval/_std/mbedtls/PkContext.hx
  std/eval/_std/mbedtls/Ssl.hx
  std/eval/_std/mbedtls/SslAuthmode.hx
  std/eval/_std/mbedtls/SslEndpoint.hx
  std/eval/_std/mbedtls/SslPreset.hx
  std/eval/_std/mbedtls/SslTransport.hx
  std/eval/_std/mbedtls/X509Crt.hx
  std/eval/_std/sys/net/Socket.hx
  std/eval/_std/sys/ssl/Certificate.hx
  std/eval/_std/sys/ssl/Key.hx
  std/eval/_std/sys/ssl/Mbedtls.hx
  std/eval/_std/sys/ssl/Socket.hx
  std/eval/vm/NativeSocket.hx
  std/sys/Http.hx
  tests/Brewfile
Labels: platform-eval

#8823 Don't generate getter calls on abstracts for display requests
  src/typing/fields.ml
  tests/server/src/DisplayTests.hx
  tests/server/src/HaxeServerTestCase.hx
  tests/server/test/templates/issues/Issue8805/Main.hx
Labels: feature-ide

#8487 [cs] Add using statements via @:csUsing
  src-json/meta.json
  src/generators/gencs.ml
  tests/misc/cs/projects/Issue8487/Main1.hx
  tests/misc/cs/projects/Issue8487/Main2.hx
  tests/misc/cs/projects/Issue8487/compile-fail.hxml
  tests/misc/cs/projects/Issue8487/compile-fail.hxml.stderr
  tests/misc/cs/projects/Issue8487/compile.hxml
Labels: platform-cs

#8360 Implement @:assemblyMeta and @:assemblyStrict
  src-json/meta.json
  src/generators/gencs.ml
  src/typing/typeloadModule.ml
  tests/misc/cs/projects/Issue8347/.gitignore
  tests/misc/cs/projects/Issue8347/Main.hx
  tests/misc/cs/projects/Issue8347/compile-fail.hxml
  tests/misc/cs/projects/Issue8347/compile-fail.hxml.stderr
  tests/misc/cs/projects/Issue8347/compile.hxml
  tests/misc/cs/projects/Issue8347/src/fail/NotFirstType.hx
  tests/misc/cs/projects/Issue8347/src/pack/Main.hx
Labels: waiting-for-feedback

#8476 Hold error/warning messages while trying to unify call arguments
  src/compiler/haxe.ml
  src/context/common.ml
  src/typing/calls.ml
  src/typing/typer.ml
  tests/misc/projects/Issue5522/Main.hx
  tests/misc/projects/Issue5522/compile.hxml
  tests/misc/projects/Issue5522/compile.hxml.stderr
  tests/misc/projects/Issue8283/compile-fail.hxml.stderr
Labels: waiting-for-feedback

#9048 [hl] update sqlite working with BLOB
  std/hl/_std/sys/db/Sqlite.hx
Labels: platform-hl
